name: videocall
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  country_picker: ^2.0.26
  flutter_riverpod: ^2.5.1
  image_picker: ^1.1.2
  flutter_contacts: ^1.1.9+2
  uuid: ^4.5.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  cached_video_player: ^2.0.4
  emoji_picker_flutter: ^3.1.0
  enough_giphy_flutter: ^0.4.1
  flutter_sound: ^9.16.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  swipe_to: ^1.0.6
  story_view: ^0.16.0
  agora_uikit: ^1.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgroundImage.png
    - assets/bg.png
